timestamp: "uto 17.06.2025. 11:59:30"
algorithm: "AES"
bits: "192"
output_folder: "keys\\symmetric-encryption\\AES\\AES192"
generated_files:
- file: key.bin\n  sha256: 354cf65a348684fccb4c68d46086fa80ef66a248dff60bb4d7eba23f2b4e9041\n- file: key.bin\n  sha256: CertUtil:\n
