timestamp: "ned 15.06.2025. 18:56:50"
algorithm: "AES"
bits: "256"
output_folder: "keys\\symmetric-encryption\\AES\\AES256"
generated_files:
- file: key.bin\n  sha256: f56bd32ffd47bf810889fa8b686cf4c1762644cffa84a44b546d8be27fbd8512\n- file: key.bin\n  sha256: CertUtil:\n
