algorithm: AES
bits: '128'
generated_files:
- file: key.bin
  sha256: fef0068dd05d6f4f9fe7d5b5c92a899cbceb95ace2832d946c6ceef9f6abba66
host: DESKTOP-EO2KI6T
output_folder: keys\symmetric-encryption\AES\AES128
python_version: 3.13.2
timestamp: Tue 17.06.2025. 12:27:09
user: Dimitrije
