algorithm: AES
bits: '192'
generated_files:
- file: key.bin
  sha256: 411fa0bd1b95cba59100f5a86fb416dbb8ddeed8e473c2d0ffbcc6745a0bd09e
host: DESKTOP-EO2KI6T
output_folder: keys\symmetric-encryption\AES\AES192
python_version: 3.13.2
timestamp: Tue 17.06.2025. 12:27:09
user: Dimitrije
