algorithm: AES
bits: '256'
generated_files:
- file: key.bin
  sha256: 20ca00639c8aac5a36172df781d1dbec0bfceb65ab9d6737cb62027aff28db5e
output_folder: keys\\symmetric-encryption\\AES\\AES256
timestamp: Tue 17.06.2025. 12:18:14
